apiVersion: v1
kind: Service
metadata:
        name: back
spec:
        selector:
                app: back
        ports:
                - protocol: TCP
                  port: 9090
                  targetPort: 9090
        type: ClusterIP
