apiVersion: v1
kind: Service
metadata:
        name: back
spec:
        selector:
                app: back
        ports:
                - protocol: TCP
                  port: 8081
                  targetPort: 8081
        type: ClusterIP
