apiVersion: v1
kind: ConfigMap
metadata:
        name: nginx-config
data:
        default.conf: |
                server {
                        listen 80;
                        location / {
                                proxy_pass http://front:3000;
                        }
                        location /api/ {
                                proxy_pass http://back:9090;
                        }
                }
                
